# Generated by Django 5.1.2 on 2024-10-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_unit', models.CharField(max_length=60)),
                ('logradouro', models.CharField(blank=True, choices=[('Rua', 'Rua'), ('AV', 'Avenida')], max_length=50, null=True)),
                ('adress', models.CharField(max_length=120)),
                ('number_adress', models.IntegerField(blank=True)),
                ('cep', models.CharField(max_length=9)),
            ],
        ),
    ]
