# Generated by Django 5.1.2 on 2024-10-23 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_active_user_admin_user_birthday_user_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_account', to='accounts.unit'),
        ),
    ]
