# Generated by Django 5.1.2 on 2024-11-05 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('motivo', models.CharField(choices=[('TDM', 'DOMINGO TRABALHADO'), ('CCG', 'COMBINADO GESTOR')])),
                ('status_folga', models.CharField(choices=[('PEN', 'PENDENTE'), ('APR', 'APROVADO'), ('REC', 'RECUSADO')], default='PENDENTE')),
                ('folga_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folga_pessoa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
