# Generated by Django 5.1.2 on 2024-11-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folga',
            name='motivo',
            field=models.CharField(choices=[('TDM', 'DOMINGO TRABALHADO'), ('CCG', 'COMBINADO GESTOR')], max_length=25),
        ),
        migrations.AlterField(
            model_name='folga',
            name='status_folga',
            field=models.CharField(choices=[('PEN', 'PENDENTE'), ('APR', 'APROVADO'), ('REC', 'RECUSADO')], default='PENDENTE', max_length=25),
        ),
    ]
