# Generated by Django 5.1.2 on 2024-12-16 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_acontuser_path'),
        ('aplication', '0003_alter_folga_motivo_alter_folga_status_folga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='folga',
            name='motivo',
            field=models.CharField(choices=[('DOMINGO TRABALHADO', 'TRABALHADO'), ('COMBINADO GESTOR', 'COMBINADO'), ('OUTROS', 'OUTROS')], max_length=25),
        ),
        migrations.AlterField(
            model_name='folga',
            name='status_folga',
            field=models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('APROVADO', 'APROVADO'), ('RECUSADO', 'RECUSADO')], default='PENDENTE', max_length=25),
        ),
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_vacation', models.DateField(unique=True, verbose_name='Data inicio:')),
                ('end_vacation', models.DateField(verbose_name='Data Fim')),
                ('month', models.CharField(blank=True, default='', max_length=250)),
                ('pessoa_vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferias_pessoa', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferias_unidade', to='accounts.unit', verbose_name='Unidade')),
            ],
        ),
    ]
