# Generated by Django 5.1.2 on 2024-11-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0003_alter_folga_motivo_alter_folga_status_folga'),
    ]

    operations = [
        migrations.AddField(
            model_name='folga',
            name='date_created',
            field=models.DateField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='folga',
            name='date_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
