# Generated by Django 5.1.2 on 2024-11-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0004_folga_date_created_folga_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folga',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='folga',
            name='day',
            field=models.DateField(unique=True),
        ),
    ]
