# Generated by Django 5.1.2 on 2024-11-10 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_unit_logradouro'),
        ('aplication', '0005_alter_folga_date_created_alter_folga_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='folga',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='folga_unidade', to='accounts.unit'),
            preserve_default=False,
        ),
    ]
