# Generated by Django 5.1.2 on 2024-11-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0006_folga_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='folga',
            name='observacao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
