# Generated by Django 5.1.2 on 2024-11-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0007_folga_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folga',
            name='observacao',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Observação:'),
        ),
    ]
