# Generated by Django 5.1.2 on 2024-11-13 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0009_alter_folga_motivo_alter_folga_status_folga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='folga',
            name='folga_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folga_pessoa', to=settings.AUTH_USER_MODEL),
        ),
    ]
