# Generated by Django 5.1.2 on 2024-11-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0010_alter_folga_folga_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folga',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='folga',
            name='observacao',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Observação:'),
        ),
    ]
