# Generated by Django 5.1.2 on 2024-12-02 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_acontuser_path'),
        ('aplication', '0011_alter_folga_day_alter_folga_observacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_vacation', models.DateField()),
                ('end_vacation', models.DateField()),
                ('pessoa_vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferias_pessoa', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferias_unidade', to='accounts.unit')),
            ],
        ),
    ]
