# Generated by Django 5.1.2 on 2024-12-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0013_ferias_month_alter_ferias_end_vacation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferias',
            name='year',
            field=models.CharField(blank=True, default=''),
        ),
    ]
